# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from start_frame import Ui_Form
from site_widget import site_Form



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # Add this layout to the central widget
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)

        # Create an instance of the form UI and add it to the main window
        self.formWidget = QtWidgets.QWidget(self.centralwidget)
        self.form_ui = Ui_Form()
        self.form_ui.setupUi(self.formWidget)

        # Add the form widget to the layout
        self.layout.addWidget(self.formWidget)

        # connect start button to load a new widget
        self.form_ui.startButton.clicked.connect(self.load_site_form)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def load_site_form(self, MainWindow):
        # remove current form widget from layout
        self.layout.removeWidget(self.formWidget)
        self.formWidget.deleteLater()

        # create new widget and setup it's ui
        self.newWidget = QtWidgets.QWidget(self.centralwidget)
        self.new_ui = site_Form()
        self.new_ui.setupUi(self.newWidget)

        # bring in the widget
        self.layout.addWidget(self.newWidget)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
